// Real Huesca locations, events, businesses, and content
// This data is used across the app for demos

export const HUESCA_NEIGHBORHOODS = [
  "Centro", "Casco Antiguo", "San Lorenzo", "Santiago", "Perpetuo Socorro",
  "María Auxiliadora", "Santo Domingo", "Encarnación", "Sancho Ramírez",
];

export const HUESCA_LANDMARKS = [
  "Catedral de Huesca", "Parque Miguel Servet", "Plaza Navarra",
  "Plaza López Allué", "Plaza Luis López Allué", "Calle Coso Alto",
  "Castillo de Loarre", "Mallos de Riglos", "Monasterio de San Juan de la Peña",
  "Salto de Roldán", "Ermita de Salas", "Río Isuela",
];

export const HUESCA_POSTS = [
  {
    id: 1,
    user_id: 1,
    title: null,
    body: "Acabo de probar el nuevo menú de Tatau Bistro en la Calle Coso Alto. Las croquetas de rabo de toro son espectaculares. Highly recommend si buscáis algo especial en el casco antiguo 🍽️",
    image_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    video_url: null,
    post_type: "post" as const,
    location: null,
    salary: null,
    event_date: null,
    event_month: null,
    attendees: 0,
    replies_count: 0,
    last_activity: null,
    likes_count: 34,
    comments_count: 12,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 2,
    user_id: 2,
    title: "¿Alguien se apunta al Salto de Roldán este finde?",
    body: "Hola a todos! Estoy organizando una ruta al Salto de Roldán para este sábado por la mañana. Salida a las 8:00 desde el parking del Parque Miguel Servet. Dificultad media-alta, unas 4 horas. Llevad agua, comida y buen ánimo! ¿Quién se apunta?",
    image_url: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    video_url: null,
    post_type: "forum" as const,
    location: null,
    salary: null,
    event_date: null,
    event_month: null,
    attendees: 0,
    replies_count: 18,
    last_activity: new Date(Date.now() - 1200000).toISOString(),
    likes_count: 27,
    comments_count: 18,
    created_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 3,
    user_id: 3,
    title: "Camarero/a para Las Torres - Jornada completa",
    body: "Restaurante Las Torres busca incorporar camarero/a con experiencia mínima de 2 años. Ambiente profesional, buen equipo y posibilidad de crecimiento. Imprescindible don de gentes y pasión por la hostelería.",
    image_url: null,
    video_url: null,
    post_type: "job" as const,
    location: "Calle María Auxiliadora 3",
    salary: "1.400€/mes + propinas",
    event_date: null,
    event_month: null,
    attendees: 0,
    replies_count: 0,
    last_activity: null,
    likes_count: 8,
    comments_count: 4,
    created_at: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 4,
    user_id: 4,
    title: "Fiestas de San Lorenzo 2026",
    body: "¡Ya tenemos programa oficial! Del 9 al 15 de agosto disfrutaremos de las Fiestas de San Lorenzo. Este año contaremos con conciertos en la Plaza de Toros, verbenas en la Plaza López Allué, procesión del santo, danzantes y mucho más. ¡No os lo perdáis!",
    image_url: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    video_url: null,
    post_type: "event" as const,
    location: "Plaza López Allué",
    salary: null,
    event_date: new Date(2026, 7, 9).toISOString(),
    event_month: "Agosto",
    attendees: 247,
    replies_count: 0,
    last_activity: null,
    likes_count: 189,
    comments_count: 42,
    created_at: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: 5,
    user_id: 5,
    title: null,
    body: "Atardecer desde el Mirador de los Mallos de Riglos. No hay palabras para describir esta vista 🌄 Huesca tiene rincones mágicos que merecen ser descubiertos.",
    image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    video_url: null,
    post_type: "post" as const,
    location: null,
    salary: null,
    event_date: null,
    event_month: null,
    attendees: 0,
    replies_count: 0,
    last_activity: null,
    likes_count: 142,
    comments_count: 28,
    created_at: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 6,
    user_id: 6,
    title: "Festival Periferias 2026",
    body: "Ya está abierta la convocatoria para el Festival Periferias de Huesca. Este año el tema es 'Conexiones'. Música, arte, literatura y performance del 30 de octubre al 5 de noviembre en diferentes espacios de la ciudad.",
    image_url: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&q=80",
    video_url: null,
    post_type: "event" as const,
    location: "Centro Cultural Matadero",
    salary: null,
    event_date: new Date(2026, 9, 30).toISOString(),
    event_month: "Octubre",
    attendees: 89,
    replies_count: 0,
    last_activity: null,
    likes_count: 67,
    comments_count: 14,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 7,
    user_id: 7,
    title: "¿Mejor sitio para tomar chocolate con churros en Huesca?",
    body: "Amigos, estoy buscando recomendaciones para un chocolate con churros decente. He probado varios sitios pero ninguno me convence del todo. ¿Dónde vais vosotros?",
    image_url: null,
    video_url: null,
    post_type: "forum" as const,
    location: null,
    salary: null,
    event_date: null,
    event_month: null,
    attendees: 0,
    replies_count: 34,
    last_activity: new Date(Date.now() - 300000).toISOString(),
    likes_count: 19,
    comments_count: 34,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const HUESCA_USERS = [
  { id: 1, name: "María García", username: "mariagarcia", bio: "Fotógrafa callejera y amante del buen café ☕", avatar_url: null, is_verified: false, posts_count: 87, followers_count: 432, following_count: 198 },
  { id: 2, name: "Pablo Torres", username: "pablotorres", bio: "Senderista empedernido. Pirineos en el corazón 🏔️", avatar_url: null, is_verified: false, posts_count: 34, followers_count: 215, following_count: 180 },
  { id: 3, name: "Restaurante Las Torres", username: "lastorres", bio: "Cocina aragonesa de autor desde 1970. Estrella Michelin", avatar_url: null, is_verified: true, posts_count: 128, followers_count: 1240, following_count: 45 },
  { id: 4, name: "Ayuntamiento de Huesca", username: "ayuntamientohuesca", bio: "Cuenta oficial del Ayuntamiento de Huesca", avatar_url: null, is_verified: true, posts_count: 456, followers_count: 5230, following_count: 89 },
  { id: 5, name: "Elena Ruiz", username: "elenaruiz", bio: "Diseñadora y amante de los atardeceres oscenses 🌅", avatar_url: null, is_verified: false, posts_count: 156, followers_count: 678, following_count: 290 },
  { id: 6, name: "Festival Periferias", username: "periferias", bio: "Festival de música, arte y literatura de Huesca", avatar_url: null, is_verified: true, posts_count: 67, followers_count: 2890, following_count: 120 },
  { id: 7, name: "Carlos Mendez", username: "carlosmendez", bio: "Runner de Huesca. Cada día una ruta nueva 🏃", avatar_url: null, is_verified: false, posts_count: 45, followers_count: 189, following_count: 234 },
  { id: 8, name: "Café Vienés", username: "cafevienes", bio: "Café histórico de Huesca desde 1911", avatar_url: null, is_verified: true, posts_count: 89, followers_count: 945, following_count: 23 },
];

export const HUESCA_SHOPS = [
  {
    id: 1, name: "Tatau Bistro", category: "Restaurantes", address: "Calle Coso Alto 12",
    description: "Cocina aragonesa creativa en el corazón de Huesca. Platos de temporada, producto local.",
    opening_hours: "Mar-Sáb 13:00-16:00, 20:30-23:30",
    phone: "+34 974 045 345", email: "info@tatau.es",
    image_url: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    logo_url: null, rating: 4.9, is_featured: true, owner_id: 3,
  },
  {
    id: 2, name: "Café Vienés", category: "Cafetería", address: "Plaza López Allué 4",
    description: "Café histórico desde 1911. Churros caseros, repostería tradicional y el mejor chocolate.",
    opening_hours: "Lun-Dom 8:00-22:00",
    phone: "+34 974 220 056", email: null,
    image_url: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800&q=80",
    logo_url: null, rating: 4.8, is_featured: true, owner_id: 8,
  },
  {
    id: 3, name: "Librería Anónima", category: "Librería", address: "Calle Cabestany 19",
    description: "Librería independiente con selección cuidada. Recomendaciones personalizadas y presentaciones.",
    opening_hours: "Lun-Sáb 10:00-14:00, 17:00-20:30",
    phone: "+34 974 227 820", email: "info@libreriaanonima.com",
    image_url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80",
    logo_url: null, rating: 4.7, is_featured: true, owner_id: 9,
  },
  {
    id: 4, name: "Restaurante Lillas Pastia", category: "Restaurantes", address: "Plaza de Navarra 4",
    description: "Alta cocina en el Casino de Huesca. Experiencia gastronómica única con tradición aragonesa.",
    opening_hours: "Mar-Sáb 13:30-15:30, 20:30-22:30",
    phone: "+34 974 211 691", email: "info@lillaspastia.es",
    image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    logo_url: null, rating: 4.6, is_featured: false, owner_id: 10,
  },
  {
    id: 5, name: "Panadería La Confianza", category: "Panadería", address: "Calle Ramón y Cajal 17",
    description: "Panadería tradicional desde 1856. Pan artesano cada mañana, empanadas y pastas.",
    opening_hours: "Lun-Sáb 7:00-14:00, 17:00-20:00",
    phone: "+34 974 211 109", email: null,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
    logo_url: null, rating: 4.9, is_featured: false, owner_id: 11,
  },
  {
    id: 6, name: "Óptica Oscense", category: "Salud", address: "Coso Bajo 22",
    description: "Óptica moderna con las mejores marcas. Revisiones gratuitas y atención personalizada.",
    opening_hours: "Lun-Vie 9:30-13:30, 17:00-20:00, Sáb 10:00-13:30",
    phone: "+34 974 229 543", email: "info@opticaoscense.es",
    image_url: "https://images.unsplash.com/photo-1577744486770-020ab432da65?w=800&q=80",
    logo_url: null, rating: 4.7, is_featured: false, owner_id: 12,
  },
  {
    id: 7, name: "El Rincón del Jamón", category: "Alimentación", address: "Plaza Navarra 8",
    description: "Los mejores jamones y embutidos de la provincia. Tienda gourmet con degustación.",
    opening_hours: "Lun-Sáb 9:00-14:00, 17:30-20:30",
    phone: "+34 974 213 678", email: null,
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    logo_url: null, rating: 4.8, is_featured: false, owner_id: 13,
  },
  {
    id: 8, name: "Boulder Huesca", category: "Deportes", address: "Carretera de Sabiñánigo Km 2",
    description: "Centro de escalada indoor más grande de Aragón. Rutas para todos los niveles.",
    opening_hours: "Lun-Vie 10:00-23:00, Sáb-Dom 10:00-21:00",
    phone: "+34 974 555 123", email: "info@boulderhuesca.com",
    image_url: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80",
    logo_url: null, rating: 4.9, is_featured: true, owner_id: 14,
  },
];

export const HUESCA_COMMUNITIES = [
  {
    id: 1, name: "Senderistas de Huesca", description: "Para todos los que amamos las rutas por los Pirineos, Guara y los alrededores de Huesca. Organizamos salidas semanales.",
    category: "Deportes", members_count: 542, image_url: null, status: "public", featured: true,
  },
  {
    id: 2, name: "Gastronomía Oscense", description: "Amantes de la cocina aragonesa. Recomendaciones, recetas y los mejores restaurantes de Huesca.",
    category: "Gastronomía", members_count: 867, image_url: null, status: "public", featured: true,
  },
  {
    id: 3, name: "Runners Huesca", description: "Grupo de corredores de Huesca. Entrenamientos grupales en el Parque Miguel Servet y alrededores.",
    category: "Deportes", members_count: 312, image_url: null, status: "public", featured: true,
  },
  {
    id: 4, name: "Fotógrafos de Huesca", description: "Comparte tus mejores fotos de Huesca y provincia. Salidas fotográficas y workshops.",
    category: "Arte y Cultura", members_count: 234, image_url: null, status: "public", featured: false,
  },
  {
    id: 5, name: "Padres y Madres Huesca", description: "Red de familias de Huesca para compartir consejos, actividades y organizar encuentros infantiles.",
    category: "Familia", members_count: 456, image_url: null, status: "public", featured: false,
  },
  {
    id: 6, name: "Emprendedores Huesca", description: "Networking para emprendedores y profesionales de Huesca. Talleres mensuales y apoyo mutuo.",
    category: "Negocios", members_count: 189, image_url: null, status: "private", featured: false,
  },
  {
    id: 7, name: "Escalada Mallos Riglos", description: "Comunidad de escaladores de los Mallos de Riglos. Partners, rutas y seguridad en la montaña.",
    category: "Deportes", members_count: 178, image_url: null, status: "public", featured: false,
  },
  {
    id: 8, name: "Bookcrossing Huesca", description: "Intercambio de libros entre lectores de Huesca. Clubs de lectura y recomendaciones.",
    category: "Arte y Cultura", members_count: 143, image_url: null, status: "public", featured: false,
  },
];

export const HUESCA_EVENTS = [
  {
    id: 1, title: "Fiestas de San Lorenzo",
    description: "Las fiestas mayores de Huesca en honor a su patrón. Conciertos, procesiones, verbenas, danzantes y mucho más durante una semana inolvidable.",
    location: "Centro de Huesca", date: "9-15 de Agosto", time: "Todo el día",
    attendees: 2847, image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    category: "Fiestas",
  },
  {
    id: 2, title: "Festival Periferias 2026",
    description: "Festival multidisciplinar de música, arte, literatura y performance. Referente cultural del otoño oscense.",
    location: "Centro Cultural Matadero", date: "30 Oct - 5 Nov", time: "Diferentes horarios",
    attendees: 892, image: "https://images.unsplash.com/photo-1501612780327-45045538702b?w=800&q=80",
    category: "Música",
  },
  {
    id: 3, title: "Mercado Medieval de Huesca",
    description: "Vuelve el mercado medieval a las calles del casco antiguo. Artesanía, gastronomía y espectáculos de época.",
    location: "Casco Antiguo", date: "Sáb 12 - Dom 13 Abr", time: "10:00 - 22:00",
    attendees: 567, image: "https://images.unsplash.com/photo-1533903345306-15d1c30952de?w=800&q=80",
    category: "Comunidad",
  },
  {
    id: 4, title: "Carrera Popular San Jorge",
    description: "Carrera popular anual por las calles de Huesca. 10K y 5K para todos los niveles. Inscripciones abiertas.",
    location: "Parque Miguel Servet", date: "Dom 26 Abr", time: "10:00",
    attendees: 1234, image: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800&q=80",
    category: "Deportes",
  },
  {
    id: 5, title: "Concierto en la Catedral",
    description: "Concierto de música sacra en la Catedral de Huesca. Obras de Tomás Luis de Victoria y J.S. Bach.",
    location: "Catedral de Huesca", date: "Vie 18 Abr", time: "20:30",
    attendees: 234, image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
    category: "Música",
  },
  {
    id: 6, title: "Feria del Libro de Huesca",
    description: "Edición anual de la Feria del Libro en la Plaza de López Allué. Firma de libros, presentaciones y talleres infantiles.",
    location: "Plaza López Allué", date: "2-10 Mayo", time: "10:00 - 21:00",
    attendees: 678, image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    category: "Arte",
  },
];

export const HUESCA_JOBS = [
  {
    id: 1, title: "Camarero/a para Las Torres", body: "Restaurante con estrella Michelin busca camarero/a con experiencia. Formación continua, buen equipo y salario competitivo.",
    company: "Restaurante Las Torres", location: "María Auxiliadora 3", salary: "1.400€/mes + propinas", type: "Jornada completa", posted: "hace 2h",
  },
  {
    id: 2, title: "Desarrollador Web Full-Stack", body: "Startup tecnológica busca desarrollador con experiencia en React, Node.js y PostgreSQL. Trabajo híbrido en oficinas del PTA.",
    company: "Cluster TIC Aragón", location: "Parque Tecnológico Walqa", salary: "35-45K€/año", type: "Jornada completa", posted: "hace 5h",
  },
  {
    id: 3, title: "Monitor/a de escalada", body: "Boulder Huesca busca monitor/a titulado para impartir clases de iniciación y perfeccionamiento.",
    company: "Boulder Huesca", location: "Ctra. Sabiñánigo Km 2", salary: "15€/h", type: "Media jornada", posted: "hace 1d",
  },
  {
    id: 4, title: "Dependiente/a Librería", body: "Librería Anónima busca librero/a apasionado/a por los libros. Conocimiento de literatura y atención al cliente.",
    company: "Librería Anónima", location: "Calle Cabestany 19", salary: "1.100€/mes", type: "Media jornada", posted: "hace 2d",
  },
  {
    id: 5, title: "Guía turístico/a", body: "Oficina de Turismo de Huesca busca guías para temporada alta. Imprescindible inglés y francés.",
    company: "Turismo Huesca", location: "Plaza López Allué", salary: "1.300€/mes", type: "Temporal", posted: "hace 3d",
  },
  {
    id: 6, title: "Fisioterapeuta", body: "Clínica Fisio Huesca busca fisioterapeuta deportivo para unirse al equipo. Especialidad en running y escalada valorada.",
    company: "Fisio Huesca", location: "Calle Zaragoza 18", salary: "1.800€/mes", type: "Jornada completa", posted: "hace 4d",
  },
];
